# Module 5 Lesson 1

We will cover Module 5 Lesson 1
- Reducing the dimensionality of data sets
- Feature engineering

**Problem Statement & Data Description**

*Client: ABC Retail, Incorporated, rest-of-the-world division* 

***Project name: Online retail sales analysis*** 

An online retailer, ABC, Inc., operates in nearly 100 countries worldwide, selling furniture, office supplies and technology products to customers in three segments: consumer, corporate and home office. ABC, Inc. is a US-based company, and it has two major divisions: US and rest of the world. We are working with the rest of the world division of the company. 

They have provided us with online sales transaction data from 2011 to 2014.

We are given 3 datasets:-

1. Data on each sale; 51290 records; all data in US dollars
It contains fields like
**order_id** (identifier) ,order_date ,ship_date ,ship_mode ,**customer_id**(identifier) ,product_id ,category ,sub_category ,product_name ,sales ,quantity ,discount ,profit ,shipping_cost ,order_priority ,**vendor_code** (identifier) 


2. Data on the customers; 1590 records 
It contains fields like
**customer_id** (identifier) ,customer_name ,city ,state ,country ,postal_code ,segment ,market ,region 

3. Data on vendors who supply the retailer; 65 records 
It contains fields like
vendor ,**vendor_code** (identifier) 

We need to analyze the data and need to provide answer to different questions asked by company officials.

In [1]:
#reading the data, libraries.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
# Use the warning filter context manager to temporarily suppress warnings
warnings.filterwarnings("ignore")

sales = pd.read_csv('sales_data.csv')
cust = pd.read_csv(r'customers.csv',encoding='iso-8859-1')
vend = pd.read_csv(r'vendors.csv')
sales.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,vendor_code
0,1,MX-2014-143658,02/10/2014,06/10/2014,Standard Class,SC-20575,OFF-LA-10002782,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,VE_001
1,2,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-FU-10004015,Furniture,Furnishings,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,VE_002
2,3,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-BO-10002352,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,VE_003
3,4,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-BI-10004428,Office Supplies,Binders,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,VE_004
4,5,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-AR-10004594,Office Supplies,Art,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,VE_005

In [2]:
sales=sales.merge(cust,on='customer_id',how='left')
sales.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,category,sub_category,product_name,...,order_priority,vendor_code,customer_name,city,state,country,postal_code,segment,market,region
0,1,MX-2014-143658,02/10/2014,06/10/2014,Standard Class,SC-20575,OFF-LA-10002782,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",...,Medium,VE_001,Sonia Cooley,Mexico City,Distrito Federal,Mexico,NaN,Consumer,LATAM,LATAM-North
1,2,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-FU-10004015,Furniture,Furnishings,"Tenex Clock, Durable",...,Medium,VE_002,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South
2,3,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-BO-10002352,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",...,Medium,VE_003,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South
3,4,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-BI-10004428,Office Supplies,Binders,"Cardinal Binder, Clear",...,Medium,VE_004,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South
4,5,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-AR-10004594,Office Supplies,Art,"Sanford Canvas, Water Color",...,Medium,VE_005,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South

In [10]:
sales['order_priority'].unique()

array(['Medium', 'Low', 'High', nan, 'Critical'], dtype=object)

### Q.1. Create a new feature which will give 50% weight to quantities sold in critical priority, 25% weight to quantities sold in high priority,10 % weight to quantities sold in medium priority,5 % weight to quantities sold in medium priority

In [14]:
# write your code here
# sales['weighted_quantity_sold']= sales.apply(lambda x:0.5*x['quantity'] if x['order_priority']=='Critical' else 0.25*x['quantity'] if  x['order_priority']=='High' else 0.1*x['quantity'] if  x['order_priority']=='Medium' else 0.05*x['quantity'] if  x['order_priority']=='Low' else 0 ,axis=1)
# sales['weighted_quantity_sold'].describe()
def weighted_qty(row):
    if row['order_priority'] == 'Critical':
        return row['quantity']*0.50
    elif row['order_priority'] == 'High':
        return row['quantity']*0.25
    elif row['order_priority'] == 'Medium':
        return row['quantity']*0.10
    elif row['order_priority'] == 'Low':
        return row['quantity']*0.05
    else:
        return 0
    
data = sales.copy()
data['weighted_quantity_sold'] = data.apply(weighted_qty, axis=1)
data.describe()

,row_id,sales,quantity,discount,profit,shipping_cost,postal_code,weighted_quantity_sold
count,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,0.0,51290.000000
mean,25645.50000,246.490581,3.476545,0.142908,28.610982,26.375915,NaN,0.590340
std,14806.29199,487.565361,2.278766,0.212280,174.340972,57.296804,NaN,0.624533
min,1.00000,0.444000,1.000000,0.000000,-6599.978000,0.000000,NaN,0.000000
25%,12823.25000,30.758625,2.000000,0.000000,0.000000,2.610000,NaN,0.200000
50%,25645.50000,85.053000,3.000000,0.000000,9.240000,7.790000,NaN,0.400000
75%,38467.75000,251.053200,5.000000,0.200000,36.810000,24.450000,NaN,0.750000
max,51290.00000,22638.480000,14.000000,0.850000,8399.976000,933.570000,NaN,7.000000

### Q.2.Define a function to categorize profit values
Here we will be using the map function.

In [16]:
# write your code here
data = sales.copy()
data['profit_category'] = data['profit'].map(lambda x: 'Profitable' if x>0 else 'Loss' if x <0 else 'No Profit')
data.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,category,sub_category,product_name,...,vendor_code,customer_name,city,state,country,postal_code,segment,market,region,profit_category
0,1,MX-2014-143658,02/10/2014,06/10/2014,Standard Class,SC-20575,OFF-LA-10002782,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",...,VE_001,Sonia Cooley,Mexico City,Distrito Federal,Mexico,NaN,Consumer,LATAM,LATAM-North,Profitable
1,2,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-FU-10004015,Furniture,Furnishings,"Tenex Clock, Durable",...,VE_002,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,Profitable
2,3,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-BO-10002352,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",...,VE_003,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,Profitable
3,4,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-BI-10004428,Office Supplies,Binders,"Cardinal Binder, Clear",...,VE_004,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,Profitable
4,5,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-AR-10004594,Office Supplies,Art,"Sanford Canvas, Water Color",...,VE_005,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,Profitable

### Q.3) Define a function to calculate Shipping cost per item

In [18]:
# write your code here
data = sales.copy()
data['shipping_cost/item'] = data.apply(lambda row: row['shipping_cost']/row['quantity'],axis=1)
data.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,category,sub_category,product_name,...,vendor_code,customer_name,city,state,country,postal_code,segment,market,region,shipping_cost/item
0,1,MX-2014-143658,02/10/2014,06/10/2014,Standard Class,SC-20575,OFF-LA-10002782,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",...,VE_001,Sonia Cooley,Mexico City,Distrito Federal,Mexico,NaN,Consumer,LATAM,LATAM-North,0.343333
1,2,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-FU-10004015,Furniture,Furnishings,"Tenex Clock, Durable",...,VE_002,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,1.681250
2,3,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-BO-10002352,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",...,VE_003,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,4.815000
3,4,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-BI-10004428,Office Supplies,Binders,"Cardinal Binder, Clear",...,VE_004,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,0.342500
4,5,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-AR-10004594,Office Supplies,Art,"Sanford Canvas, Water Color",...,VE_005,Kelly Williams,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,1.895000

### Q.4) Define a function to calculate cumulative profit

In [26]:
# write your code here
data = sales.copy()
from functools import reduce

# Use the map function to apply the calculate_profit function to the 'Profit' column
profit_list = data['profit']

# Define a function to calculate the sum of a list
def calculate_sum(lst):
    return reduce(lambda x, y: x + y, lst)

# Use the reduce function to calculate the total profit
total_profit = calculate_sum(profit_list)
total_profit

1467457.2912799797

In [27]:
sales['profit'].sum()

1467457.29128

## Solutions

In [7]:
# Q.1)  Applying lambda function
sales['weighted_quantity_sold']= sales.apply(lambda x:0.5*x['quantity'] if x['order_priority']=='Critical' else 0.25*x['quantity'] if  x['order_priority']=='High' else 0.1*x['quantity'] if  x['order_priority']=='Medium' else 0.05*x['quantity'] if  x['order_priority']=='Low' else 0 ,axis=1)
sales['weighted_quantity_sold'].describe()

count    51290.000000
mean         0.590340
std          0.624533
min          0.000000
25%          0.200000
50%          0.400000
75%          0.750000
max          7.000000
Name: weighted_quantity_sold, dtype: float64

In [8]:
# Q.2) # Here we are supposed to make use of map function
def categorize_profit(profit):
    if profit > 0:
        return 'Profitable'
    elif profit < 0:
        return 'Loss'
    else:
        return 'No Profit'

# Apply the categorize_profit function to the 'Profit' column using map
sales['Profit_Category'] = sales['profit'].map(categorize_profit)
sales[['profit','Profit_Category']].head()

   profit Profit_Category
0    4.56      Profitable
1   90.72      Profitable
2   54.08      Profitable
3    4.96      Profitable
4   11.44      Profitable

In [9]:
#Q.3)

def Shipping_cost_per_item(row):
    return (row['shipping_cost']/row['quantity'])

# Use the assign function to add a 'Profit_Margin' column
sales = sales.assign(Shipping_cost_per_item=lambda x: Shipping_cost_per_item(x))
sales.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,category,sub_category,product_name,...,city,state,country,postal_code,segment,market,region,weighted_quantity_sold,Profit_Category,Shipping_cost_per_item
0,1,MX-2014-143658,02/10/2014,06/10/2014,Standard Class,SC-20575,OFF-LA-10002782,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",...,Mexico City,Distrito Federal,Mexico,NaN,Consumer,LATAM,LATAM-North,0.3,Profitable,0.343333
1,2,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-FU-10004015,Furniture,Furnishings,"Tenex Clock, Durable",...,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,0.8,Profitable,1.681250
2,3,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,FUR-BO-10002352,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",...,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,0.2,Profitable,4.815000
3,4,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-BI-10004428,Office Supplies,Binders,"Cardinal Binder, Clear",...,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,0.4,Profitable,0.342500
4,5,MX-2012-155047,15/10/2012,20/10/2012,Standard Class,KW-16570,OFF-AR-10004594,Office Supplies,Art,"Sanford Canvas, Water Color",...,Dos Quebradas,Risaralda,Colombia,NaN,Consumer,LATAM,LATAM-South,0.2,Profitable,1.895000

In [10]:
# Q.4)

from functools import reduce
def calculate_profit(profit):
    return profit

# Use the map function to apply the calculate_profit function to the 'Profit' column
profit_list = sales['profit'].map(calculate_profit)

# Define a function to calculate the sum of a list
def calculate_sum(lst):
    return reduce(lambda x, y: x + y, lst)

# Use the reduce function to calculate the total profit
total_profit = calculate_sum(profit_list)
total_profit

1467457.2912799797

In [11]:
sales['profit'].sum()

1467457.29128